theme: jekyll-theme-slate
title: pandaå¤§å­¦ç¿’å¸³å¤–ä¼
description: ãƒ•ãƒ©ãƒ³ã‚¹ã«æ¸¡ç±³ã§ãã‚‹ãƒãƒ£ãƒ³ã‚¹!!ğŸ¤”
avatar: '/img/pandanote_logo_square_sp_120x120.png'
google_analytics: UA-99601971-2
github:
  is_project_page: true
  owner_name: 'pandanote.info'
  owner_url: 'https://pandanote.info/'
copyright: 'Copyright 2018 and 2019, pandanote.info'
